# to build and deploy on server
on:
  release:
    types: [created]
  push:
    branches:
      - stage

name: Deploy to Server

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:  
     - name: Creating key file
       run: mkdir -p ~/.ssh && touch ~/.ssh/known_hosts
     
   
        
     - name: Install SSH Key
       uses: shimataro/ssh-key-action@v2
       
       with:
        key: ${{ secrets.SERVER_SSH_KEY }} 
        known_hosts: 'randomstringhostiureyqhfjkhkfjhfkjask'
        
     #- name: Creating key file
      # run: touch ~/.ssh/keyfile.pem && echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/keyfile.pem

    # - name: change permissions for pem file
     #  run: sudo chmod 400 ~/.ssh/keyfile.pem
    
     - name: Adding Known Hosts
       run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
       
     - name: install ssh pass
       run: sudo apt-get install sshpass
       
     - name: run test command
       run: sshpass -p ${{ secrets.SSH_PWD }} ssh root@${{ secrets.SSH_HOST }}
       
     - name: change directory
       run: cd /var/www/html
     - name: run migrations
       run: php spark migrate
       
     - name: database seed
       run: /usr/bin/php spark db:seed PlaygroundSeeder
       
