# to build and deploy on server
on:
  release:
    types: [created]

name: Deploy to Server

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:    
     - name: Adding Known Hosts
       run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

     - name: Install SSH Key
       uses: shimataro/ssh-key-action@v2
       with:
        key: ${{ secrets.SERVER_SSH_KEY }} 
        known_hosts: 'pass'
     - name: run test command
       run: ssh root@${{ secrets.SSH_HOST }}
     - name: list of disks
       run: df -h
